FROM node:18

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y wget

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN npm install

EXPOSE 3000

# CMD [ "node", "./index.js" ]
# ISSO AQUI VAI PARAR DO DOCKER-COMPOSE! (aqui passa a ser ignorado se o docker-compose existe)